version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # Install required Python packages
  build:
    commands:
      - echo "Starting build process..."
      - streamlit run app.py --headless  # Ensure app runs without manual interaction
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'  # Include all files in the build output
  discard-paths: no  # Maintain file structure in artifacts
